Query for Crime count : 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX ds: <http://data.baltimorecity.gov/resource/_8hgm-7t56/> 
PREFIX ts: <http://data.baltimorecity.gov/resource/_59fg-ary5/> 
PREFIX dsbase: <http://data.baltimorecity.gov/resource/> 
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?neighborhood1 (count(?neighborhood) AS ?count) 
WHERE { 
?element rdf:type dsbase:_8hgm-7t56; 
ds:neighborhood ?neighborhood1; 
ds:unempr13 ?unemp_rate. 
?element1 rdf:type dsbase:_59fg-ary5; 
ts:neighborhood ?neighborhood; 
filter contains(?neighborhood,?neighborhood1) 
} GROUP BY ?neighborhood1 ORDER BY ASC(?neighborhood1)